// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnalyticsController from "./analytics_controller.ts"
application.register("analytics", AnalyticsController)

import AutosubmitController from "./autosubmit_controller.ts"
application.register("autosubmit", AutosubmitController)

import ChatController from "./chat_controller.ts"
application.register("chat", ChatController)

import DatepickerController from "./datepicker_controller.ts"
application.register("datepicker", DatepickerController)

import HideController from "./hide_controller.ts"
application.register("hide", HideController)

import ImagePreviewController from "./image_preview_controller.ts"
application.register("image-preview", ImagePreviewController)

import LocationSelectController from "./location_select_controller.ts"
application.register("location-select", LocationSelectController)

import MapController from "./map_controller.ts"
application.register("map", MapController)

import NotificationController from "./notification_controller.ts"
application.register("notification", NotificationController)

import RedirectInteractionController from "./redirect_interaction_controller.ts"
application.register("redirect-interaction", RedirectInteractionController)

import ShareController from "./share_controller.ts"
application.register("share", ShareController)

import ToggleController from "./toggle_controller.ts"
application.register("toggle", ToggleController)

import ViewportClickController from "./viewport_click_controller.ts"
application.register("viewport-click", ViewportClickController)
