AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'

require:
  - rubocop-rails

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Rails:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Metrics:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/NumericPredicate:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
