version: 2
executorType: docker
containerInfo:
  - image: circleci/ruby:2.5.1-node-browsers
  - image: postgres:10
  - image: elasticsearch:5.3

stages:
  build:
    workDir: ~/goodjobs
    environment:
      RAILS_ENV: test
    steps:
      - type: checkout
      - type: shell
        name: Install System Dependencies
        command: sudo apt-get update -qq && sudo apt-get install -y build-essential
      - type: cache-restore
        key: gemfile-{{ checksum "Gemfile.lock" }}
      - type: shell
        name: Install Ruby Dependencies
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - type: shell
        name: Precompile assets
        command: bundle exec rake assets:precompile
      - type: shell
        name: Copy CK Editor plugin folder
        command: bundle exec rake ckeditor:copy:plugins
      - type: cache-save
        key: gemfile-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - type: shell
        name: Create DB
        command: bundle exec rails db:create db:migrate --trace
      - type: shell
        name: Run RSpec Tests
        command: bundle exec rspec --format documentation
      - type: shell
        name: Check Code Styleguides
        command: bundle exec rubocop
