version: '2'

services:
  postgres:
    image: 'postgres:10'
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/volumes/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
