default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 54312
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  username: <%= ENV["PG_USER"] || "postgres" %>
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || 60000 %>

development:
  <<: *default
  database: thefetishtraveller_development

test:
  <<: *default
  database: thefetishtraveller_test
