default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: <%= ENV["PG_USER"] || "postgres" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thefetishtraveller_development

test:
  <<: *default
  database: thefetishtraveller_test

production:
  <<: *default
  database: thefetishtraveller_production
