name: CI

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tft
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn
      - name: Install yarn
        run: yarn install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint
        run: bundle exec standardrb
      - name: Translations Lint
        run: bundle exec i18n-tasks health
      - name: JS Lint
        run: yarn lint
      - name: Build Assets
        run: yarn build
      - name: Create PG Database
        run: bundle exec rake db:create db:migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/tft
          RAILS_ENV: test
      - name: Build and test with Rake
        run: bundle exec rspec --format documentation
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/tft
          REDIS_URL: redis://127.0.0.1:6379
          RAILS_ENV: test
